@startuml
struct Cell
{
    + X : <color:indigo><b>int
    + Y : <color:indigo><b>intint
    --
    + {static} Zero : <color:indigo><b>Cell
    + {static} Up : <color:indigo><b>Cell
    + {static} Down : <color:indigo><b>Cell
    + {static} Right : <color:indigo><b>Cell
    + {static} Left : <color:indigo><b>Cell
    --
    + constructor : <color:indigo><b>Cell(int <color:black>x, <color:indigo><b>int <color:black><b>y)
    + {static} operator : <color:indigo><b>Cell +(Cell, Cell)
}
@enduml