@startuml

class ConsoleInput
{
    - _arrowListeners : <color:indigo><b>HashSet<IArrowListener> <color:green>new
    --
    + Subscribe<color:indigo>(<color:indigo><b>IArrowListener <color:black>listener)
    --
    + Update()
    
    
    
}

note left of ConsoleInput::Subscribe
<b>_arrowListeners.Add(listener)  
<color:green>добавляем подписчиков в список 
end note

note right of ConsoleInput::Update
метод который будет считывать ввод с консоли
<b>while (Console.KeyAvailable) 
{ 
  <b>ConsoleKeyInfo key = Console.ReadKey();
  <b>switch (key.Key) 
    <b>case ConsoleKey.UpArrow or ConsoleKey.W: 
      <b>foreach (var sub in _arrowListeners) sub.OnArrowUp(); 
      <b>break; 
    <color:green>- по четырём сторонам
}
end note
@enduml