@startuml

left to right direction


!include BaseGameLogic.puml
!include SnakeGameLogic.puml
!include IArrowListener.puml
!include SnakeDir.puml
!include ConsoleInput.puml
!include Cell.puml
!include BaseGameState.puml
!include SnakeGameplayState.puml
!include Program.puml



BaseGameLogic -[#green,thickness=5]-> IArrowListener
BaseGameLogic::InitializeInput -[#blue,thickness=2]-> ConsoleInput::Subs
SnakeGameLogic -[#green,thickness=5]-> BaseGameLogic

SnakeGameLogic::OnArrowUp -[#blue,thickness=2]-> SnakeGameplayState::SetD
SnakeGameLogic::Down -[#blue,thickness=2]-> SnakeGameplayState::SetD
SnakeGameLogic::Left -[#blue,thickness=2]-> SnakeGameplayState::SetD
SnakeGameLogic::Right -[#blue,thickness=2]-> SnakeGameplayState::SetD

SnakeGameLogic::OnArrowUp -[#blue,thickness=2]-> SnakeDir::Up
SnakeGameLogic::Down -[#blue,thickness=2]-> SnakeDir::Down
SnakeGameLogic::Left -[#blue,thickness=2]-> SnakeDir::Left
SnakeGameLogic::Right -[#blue,thickness=2]-> SnakeDir::Right

SnakeGameplayState -[#green,thickness=5]-> BaseGameState

Program::gameLogic -[#blue,thickness=2]-> BaseGameLogic::InitializeInput
Program::gameLogic -[#blue,thickness=2]-> SnakeGameLogic::Goto: после установки времени
Program::while -[#blue,thickness=2]-> SnakeGameLogic::Update
SnakeGameLogic::Update -[#blue,thickness=3]-> SnakeGameplayState::Update


@enduml