@startuml
class SnakeGameplayState
{
    - _bodyList : List<Cell> new()
    - _currentDir : SnakeDir
    - _timeToMove : float 0
    --
    + Update(float deltaTime)
    + Reset()
    + SetDirection(SnakeDir dir) => _currentDir = dir
    - ShiftTo(Cell from, SnakeDir direction) : Cell
    
}

note left of SnakeGameplayState::Update
        _timeToMove -= deltaTime;
        if (_timeToMove > 0) return;
        _timeToMove = 1f / 1f;
        Cell head = _bodyList[0];
        Cell nextCell = ShiftTo(head, _currentDir);
        _bodyList.RemoveAt(_bodyList.Count - 1);
        _bodyList.Insert(0, nextCell);
end note
note left of SnakeGameplayState::Reset
_bodyList.Clear();
_currentDir = SnakeDir.Right;
_bodyList.Add(Cell.Zero);
_timeToMove = 0; 
end note
note left of SnakeGameplayState::ShiftTo
Логика следующей ячейки вызывется в Update
end note

@enduml